//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Inclutec_BDModel", "FK_Solicitud_Estudiante", "SIFEstudiante", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITCR.Ado.ModeloAcDatos.SIFEstudiante), "SIFSolicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITCR.Ado.ModeloAcDatos.SIFSolicitud), true)]
[assembly: EdmRelationshipAttribute("Inclutec_BDModel", "FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITCR.Ado.ModeloAcDatos.SIFGrupo), "SIFGrupo_Por_Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ITCR.Ado.ModeloAcDatos.SIFGrupo_Por_Solicitud), true)]
[assembly: EdmRelationshipAttribute("Inclutec_BDModel", "FK_Grupo_Por_Solicitud_Solicitud", "SIFSolicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITCR.Ado.ModeloAcDatos.SIFSolicitud), "SIFGrupo_Por_Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ITCR.Ado.ModeloAcDatos.SIFGrupo_Por_Solicitud), true)]
[assembly: EdmRelationshipAttribute("Inclutec_BDModel", "FK_Solicitud_Periodo", "SIFPeriodo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITCR.Ado.ModeloAcDatos.SIFPeriodo), "SIFSolicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITCR.Ado.ModeloAcDatos.SIFSolicitud), true)]

#endregion

namespace ITCR.Ado.ModeloAcDatos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Inclutec_BDEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Inclutec_BDEntities object using the connection string found in the 'Inclutec_BDEntities' section of the application configuration file.
        /// </summary>
        public Inclutec_BDEntities() : base("name=Inclutec_BDEntities", "Inclutec_BDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Inclutec_BDEntities object.
        /// </summary>
        public Inclutec_BDEntities(string connectionString) : base(connectionString, "Inclutec_BDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Inclutec_BDEntities object.
        /// </summary>
        public Inclutec_BDEntities(EntityConnection connection) : base(connection, "Inclutec_BDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIFEstudiante> SIFEstudiantes
        {
            get
            {
                if ((_SIFEstudiantes == null))
                {
                    _SIFEstudiantes = base.CreateObjectSet<SIFEstudiante>("SIFEstudiantes");
                }
                return _SIFEstudiantes;
            }
        }
        private ObjectSet<SIFEstudiante> _SIFEstudiantes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIFGrupo> SIFGrupoes
        {
            get
            {
                if ((_SIFGrupoes == null))
                {
                    _SIFGrupoes = base.CreateObjectSet<SIFGrupo>("SIFGrupoes");
                }
                return _SIFGrupoes;
            }
        }
        private ObjectSet<SIFGrupo> _SIFGrupoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIFGrupo_Por_Solicitud> SIFGrupo_Por_Solicitud
        {
            get
            {
                if ((_SIFGrupo_Por_Solicitud == null))
                {
                    _SIFGrupo_Por_Solicitud = base.CreateObjectSet<SIFGrupo_Por_Solicitud>("SIFGrupo_Por_Solicitud");
                }
                return _SIFGrupo_Por_Solicitud;
            }
        }
        private ObjectSet<SIFGrupo_Por_Solicitud> _SIFGrupo_Por_Solicitud;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIFPeriodo> SIFPeriodoes
        {
            get
            {
                if ((_SIFPeriodoes == null))
                {
                    _SIFPeriodoes = base.CreateObjectSet<SIFPeriodo>("SIFPeriodoes");
                }
                return _SIFPeriodoes;
            }
        }
        private ObjectSet<SIFPeriodo> _SIFPeriodoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIFSolicitud> SIFSolicituds
        {
            get
            {
                if ((_SIFSolicituds == null))
                {
                    _SIFSolicituds = base.CreateObjectSet<SIFSolicitud>("SIFSolicituds");
                }
                return _SIFSolicituds;
            }
        }
        private ObjectSet<SIFSolicitud> _SIFSolicituds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIFEstudiantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIFEstudiantes(SIFEstudiante sIFEstudiante)
        {
            base.AddObject("SIFEstudiantes", sIFEstudiante);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIFGrupoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIFGrupoes(SIFGrupo sIFGrupo)
        {
            base.AddObject("SIFGrupoes", sIFGrupo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIFGrupo_Por_Solicitud EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIFGrupo_Por_Solicitud(SIFGrupo_Por_Solicitud sIFGrupo_Por_Solicitud)
        {
            base.AddObject("SIFGrupo_Por_Solicitud", sIFGrupo_Por_Solicitud);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIFPeriodoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIFPeriodoes(SIFPeriodo sIFPeriodo)
        {
            base.AddObject("SIFPeriodoes", sIFPeriodo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIFSolicituds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIFSolicituds(SIFSolicitud sIFSolicitud)
        {
            base.AddObject("SIFSolicituds", sIFSolicitud);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Inclutec_BDModel", Name="SIFEstudiante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIFEstudiante : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIFEstudiante object.
        /// </summary>
        /// <param name="id_Carnet">Initial value of the id_Carnet property.</param>
        /// <param name="nom_nombre">Initial value of the nom_nombre property.</param>
        /// <param name="txt_apellido_1">Initial value of the txt_apellido_1 property.</param>
        /// <param name="num_telefono">Initial value of the num_telefono property.</param>
        /// <param name="num_celular">Initial value of the num_celular property.</param>
        /// <param name="dir_email">Initial value of the dir_email property.</param>
        /// <param name="num_plan_estudios">Initial value of the num_plan_estudios property.</param>
        public static SIFEstudiante CreateSIFEstudiante(global::System.String id_Carnet, global::System.String nom_nombre, global::System.String txt_apellido_1, global::System.String num_telefono, global::System.String num_celular, global::System.String dir_email, global::System.Int32 num_plan_estudios)
        {
            SIFEstudiante sIFEstudiante = new SIFEstudiante();
            sIFEstudiante.id_Carnet = id_Carnet;
            sIFEstudiante.nom_nombre = nom_nombre;
            sIFEstudiante.txt_apellido_1 = txt_apellido_1;
            sIFEstudiante.num_telefono = num_telefono;
            sIFEstudiante.num_celular = num_celular;
            sIFEstudiante.dir_email = dir_email;
            sIFEstudiante.num_plan_estudios = num_plan_estudios;
            return sIFEstudiante;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_Carnet
        {
            get
            {
                return _id_Carnet;
            }
            set
            {
                if (_id_Carnet != value)
                {
                    Onid_CarnetChanging(value);
                    ReportPropertyChanging("id_Carnet");
                    _id_Carnet = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_Carnet");
                    Onid_CarnetChanged();
                }
            }
        }
        private global::System.String _id_Carnet;
        partial void Onid_CarnetChanging(global::System.String value);
        partial void Onid_CarnetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom_nombre
        {
            get
            {
                return _nom_nombre;
            }
            set
            {
                Onnom_nombreChanging(value);
                ReportPropertyChanging("nom_nombre");
                _nom_nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom_nombre");
                Onnom_nombreChanged();
            }
        }
        private global::System.String _nom_nombre;
        partial void Onnom_nombreChanging(global::System.String value);
        partial void Onnom_nombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String txt_apellido_1
        {
            get
            {
                return _txt_apellido_1;
            }
            set
            {
                Ontxt_apellido_1Changing(value);
                ReportPropertyChanging("txt_apellido_1");
                _txt_apellido_1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("txt_apellido_1");
                Ontxt_apellido_1Changed();
            }
        }
        private global::System.String _txt_apellido_1;
        partial void Ontxt_apellido_1Changing(global::System.String value);
        partial void Ontxt_apellido_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txt_apellido_2
        {
            get
            {
                return _txt_apellido_2;
            }
            set
            {
                Ontxt_apellido_2Changing(value);
                ReportPropertyChanging("txt_apellido_2");
                _txt_apellido_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txt_apellido_2");
                Ontxt_apellido_2Changed();
            }
        }
        private global::System.String _txt_apellido_2;
        partial void Ontxt_apellido_2Changing(global::System.String value);
        partial void Ontxt_apellido_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String num_telefono
        {
            get
            {
                return _num_telefono;
            }
            set
            {
                Onnum_telefonoChanging(value);
                ReportPropertyChanging("num_telefono");
                _num_telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("num_telefono");
                Onnum_telefonoChanged();
            }
        }
        private global::System.String _num_telefono;
        partial void Onnum_telefonoChanging(global::System.String value);
        partial void Onnum_telefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String num_celular
        {
            get
            {
                return _num_celular;
            }
            set
            {
                Onnum_celularChanging(value);
                ReportPropertyChanging("num_celular");
                _num_celular = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("num_celular");
                Onnum_celularChanged();
            }
        }
        private global::System.String _num_celular;
        partial void Onnum_celularChanging(global::System.String value);
        partial void Onnum_celularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dir_email
        {
            get
            {
                return _dir_email;
            }
            set
            {
                Ondir_emailChanging(value);
                ReportPropertyChanging("dir_email");
                _dir_email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dir_email");
                Ondir_emailChanged();
            }
        }
        private global::System.String _dir_email;
        partial void Ondir_emailChanging(global::System.String value);
        partial void Ondir_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_plan_estudios
        {
            get
            {
                return _num_plan_estudios;
            }
            set
            {
                Onnum_plan_estudiosChanging(value);
                ReportPropertyChanging("num_plan_estudios");
                _num_plan_estudios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_plan_estudios");
                Onnum_plan_estudiosChanged();
            }
        }
        private global::System.Int32 _num_plan_estudios;
        partial void Onnum_plan_estudiosChanging(global::System.Int32 value);
        partial void Onnum_plan_estudiosChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Solicitud_Estudiante", "SIFSolicitud")]
        public EntityCollection<SIFSolicitud> SIFSolicituds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SIFSolicitud>("Inclutec_BDModel.FK_Solicitud_Estudiante", "SIFSolicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SIFSolicitud>("Inclutec_BDModel.FK_Solicitud_Estudiante", "SIFSolicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Inclutec_BDModel", Name="SIFGrupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIFGrupo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIFGrupo object.
        /// </summary>
        /// <param name="id_Grupo">Initial value of the id_Grupo property.</param>
        /// <param name="num_grupo">Initial value of the num_grupo property.</param>
        /// <param name="num_cupos_extra">Initial value of the num_cupos_extra property.</param>
        public static SIFGrupo CreateSIFGrupo(global::System.Int32 id_Grupo, global::System.Int32 num_grupo, global::System.Int32 num_cupos_extra)
        {
            SIFGrupo sIFGrupo = new SIFGrupo();
            sIFGrupo.id_Grupo = id_Grupo;
            sIFGrupo.num_grupo = num_grupo;
            sIFGrupo.num_cupos_extra = num_cupos_extra;
            return sIFGrupo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Grupo
        {
            get
            {
                return _id_Grupo;
            }
            set
            {
                if (_id_Grupo != value)
                {
                    Onid_GrupoChanging(value);
                    ReportPropertyChanging("id_Grupo");
                    _id_Grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Grupo");
                    Onid_GrupoChanged();
                }
            }
        }
        private global::System.Int32 _id_Grupo;
        partial void Onid_GrupoChanging(global::System.Int32 value);
        partial void Onid_GrupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_grupo
        {
            get
            {
                return _num_grupo;
            }
            set
            {
                Onnum_grupoChanging(value);
                ReportPropertyChanging("num_grupo");
                _num_grupo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_grupo");
                Onnum_grupoChanged();
            }
        }
        private global::System.Int32 _num_grupo;
        partial void Onnum_grupoChanging(global::System.Int32 value);
        partial void Onnum_grupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_cupos_extra
        {
            get
            {
                return _num_cupos_extra;
            }
            set
            {
                Onnum_cupos_extraChanging(value);
                ReportPropertyChanging("num_cupos_extra");
                _num_cupos_extra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_cupos_extra");
                Onnum_cupos_extraChanged();
            }
        }
        private global::System.Int32 _num_cupos_extra;
        partial void Onnum_cupos_extraChanging(global::System.Int32 value);
        partial void Onnum_cupos_extraChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo_Por_Solicitud")]
        public SIFGrupo_Por_Solicitud SIFGrupo_Por_Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo_Por_Solicitud").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo_Por_Solicitud").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SIFGrupo_Por_Solicitud> SIFGrupo_Por_SolicitudReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo_Por_Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo_Por_Solicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Inclutec_BDModel", Name="SIFGrupo_Por_Solicitud")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIFGrupo_Por_Solicitud : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIFGrupo_Por_Solicitud object.
        /// </summary>
        /// <param name="id_Grupo_Por_Solicitud">Initial value of the id_Grupo_Por_Solicitud property.</param>
        /// <param name="num_prioridad">Initial value of the num_prioridad property.</param>
        /// <param name="txt_estado">Initial value of the txt_estado property.</param>
        /// <param name="fK_Grupo_idGrupo">Initial value of the FK_Grupo_idGrupo property.</param>
        /// <param name="fK_Solicitud_idSolicitud">Initial value of the FK_Solicitud_idSolicitud property.</param>
        public static SIFGrupo_Por_Solicitud CreateSIFGrupo_Por_Solicitud(global::System.Int32 id_Grupo_Por_Solicitud, global::System.Int32 num_prioridad, global::System.String txt_estado, global::System.Int32 fK_Grupo_idGrupo, global::System.Int32 fK_Solicitud_idSolicitud)
        {
            SIFGrupo_Por_Solicitud sIFGrupo_Por_Solicitud = new SIFGrupo_Por_Solicitud();
            sIFGrupo_Por_Solicitud.id_Grupo_Por_Solicitud = id_Grupo_Por_Solicitud;
            sIFGrupo_Por_Solicitud.num_prioridad = num_prioridad;
            sIFGrupo_Por_Solicitud.txt_estado = txt_estado;
            sIFGrupo_Por_Solicitud.FK_Grupo_idGrupo = fK_Grupo_idGrupo;
            sIFGrupo_Por_Solicitud.FK_Solicitud_idSolicitud = fK_Solicitud_idSolicitud;
            return sIFGrupo_Por_Solicitud;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Grupo_Por_Solicitud
        {
            get
            {
                return _id_Grupo_Por_Solicitud;
            }
            set
            {
                if (_id_Grupo_Por_Solicitud != value)
                {
                    Onid_Grupo_Por_SolicitudChanging(value);
                    ReportPropertyChanging("id_Grupo_Por_Solicitud");
                    _id_Grupo_Por_Solicitud = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Grupo_Por_Solicitud");
                    Onid_Grupo_Por_SolicitudChanged();
                }
            }
        }
        private global::System.Int32 _id_Grupo_Por_Solicitud;
        partial void Onid_Grupo_Por_SolicitudChanging(global::System.Int32 value);
        partial void Onid_Grupo_Por_SolicitudChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_prioridad
        {
            get
            {
                return _num_prioridad;
            }
            set
            {
                Onnum_prioridadChanging(value);
                ReportPropertyChanging("num_prioridad");
                _num_prioridad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_prioridad");
                Onnum_prioridadChanged();
            }
        }
        private global::System.Int32 _num_prioridad;
        partial void Onnum_prioridadChanging(global::System.Int32 value);
        partial void Onnum_prioridadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String txt_estado
        {
            get
            {
                return _txt_estado;
            }
            set
            {
                Ontxt_estadoChanging(value);
                ReportPropertyChanging("txt_estado");
                _txt_estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("txt_estado");
                Ontxt_estadoChanged();
            }
        }
        private global::System.String _txt_estado;
        partial void Ontxt_estadoChanging(global::System.String value);
        partial void Ontxt_estadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FK_Grupo_idGrupo
        {
            get
            {
                return _FK_Grupo_idGrupo;
            }
            set
            {
                OnFK_Grupo_idGrupoChanging(value);
                ReportPropertyChanging("FK_Grupo_idGrupo");
                _FK_Grupo_idGrupo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Grupo_idGrupo");
                OnFK_Grupo_idGrupoChanged();
            }
        }
        private global::System.Int32 _FK_Grupo_idGrupo;
        partial void OnFK_Grupo_idGrupoChanging(global::System.Int32 value);
        partial void OnFK_Grupo_idGrupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FK_Solicitud_idSolicitud
        {
            get
            {
                return _FK_Solicitud_idSolicitud;
            }
            set
            {
                OnFK_Solicitud_idSolicitudChanging(value);
                ReportPropertyChanging("FK_Solicitud_idSolicitud");
                _FK_Solicitud_idSolicitud = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Solicitud_idSolicitud");
                OnFK_Solicitud_idSolicitudChanged();
            }
        }
        private global::System.Int32 _FK_Solicitud_idSolicitud;
        partial void OnFK_Solicitud_idSolicitudChanging(global::System.Int32 value);
        partial void OnFK_Solicitud_idSolicitudChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo")]
        public SIFGrupo SIFGrupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SIFGrupo> SIFGrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SIFGrupo>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Grupo", "SIFGrupo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Grupo_Por_Solicitud_Solicitud", "SIFSolicitud")]
        public SIFSolicitud SIFSolicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFSolicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFSolicitud").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFSolicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFSolicitud").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SIFSolicitud> SIFSolicitudReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFSolicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFSolicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SIFSolicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFSolicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Inclutec_BDModel", Name="SIFPeriodo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIFPeriodo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIFPeriodo object.
        /// </summary>
        /// <param name="id_Periodo">Initial value of the id_Periodo property.</param>
        /// <param name="fec_inicio">Initial value of the fec_inicio property.</param>
        /// <param name="fec_fin">Initial value of the fec_fin property.</param>
        /// <param name="txt_estado">Initial value of the txt_estado property.</param>
        /// <param name="txt_modalidad">Initial value of the txt_modalidad property.</param>
        /// <param name="num_anno">Initial value of the num_anno property.</param>
        public static SIFPeriodo CreateSIFPeriodo(global::System.Int32 id_Periodo, global::System.DateTime fec_inicio, global::System.DateTime fec_fin, global::System.String txt_estado, global::System.String txt_modalidad, global::System.Int32 num_anno)
        {
            SIFPeriodo sIFPeriodo = new SIFPeriodo();
            sIFPeriodo.id_Periodo = id_Periodo;
            sIFPeriodo.fec_inicio = fec_inicio;
            sIFPeriodo.fec_fin = fec_fin;
            sIFPeriodo.txt_estado = txt_estado;
            sIFPeriodo.txt_modalidad = txt_modalidad;
            sIFPeriodo.num_anno = num_anno;
            return sIFPeriodo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Periodo
        {
            get
            {
                return _id_Periodo;
            }
            set
            {
                if (_id_Periodo != value)
                {
                    Onid_PeriodoChanging(value);
                    ReportPropertyChanging("id_Periodo");
                    _id_Periodo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Periodo");
                    Onid_PeriodoChanged();
                }
            }
        }
        private global::System.Int32 _id_Periodo;
        partial void Onid_PeriodoChanging(global::System.Int32 value);
        partial void Onid_PeriodoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fec_inicio
        {
            get
            {
                return _fec_inicio;
            }
            set
            {
                Onfec_inicioChanging(value);
                ReportPropertyChanging("fec_inicio");
                _fec_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fec_inicio");
                Onfec_inicioChanged();
            }
        }
        private global::System.DateTime _fec_inicio;
        partial void Onfec_inicioChanging(global::System.DateTime value);
        partial void Onfec_inicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fec_fin
        {
            get
            {
                return _fec_fin;
            }
            set
            {
                Onfec_finChanging(value);
                ReportPropertyChanging("fec_fin");
                _fec_fin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fec_fin");
                Onfec_finChanged();
            }
        }
        private global::System.DateTime _fec_fin;
        partial void Onfec_finChanging(global::System.DateTime value);
        partial void Onfec_finChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String txt_estado
        {
            get
            {
                return _txt_estado;
            }
            set
            {
                Ontxt_estadoChanging(value);
                ReportPropertyChanging("txt_estado");
                _txt_estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("txt_estado");
                Ontxt_estadoChanged();
            }
        }
        private global::System.String _txt_estado;
        partial void Ontxt_estadoChanging(global::System.String value);
        partial void Ontxt_estadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String txt_modalidad
        {
            get
            {
                return _txt_modalidad;
            }
            set
            {
                Ontxt_modalidadChanging(value);
                ReportPropertyChanging("txt_modalidad");
                _txt_modalidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("txt_modalidad");
                Ontxt_modalidadChanged();
            }
        }
        private global::System.String _txt_modalidad;
        partial void Ontxt_modalidadChanging(global::System.String value);
        partial void Ontxt_modalidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_anno
        {
            get
            {
                return _num_anno;
            }
            set
            {
                Onnum_annoChanging(value);
                ReportPropertyChanging("num_anno");
                _num_anno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_anno");
                Onnum_annoChanged();
            }
        }
        private global::System.Int32 _num_anno;
        partial void Onnum_annoChanging(global::System.Int32 value);
        partial void Onnum_annoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num_periodo
        {
            get
            {
                return _num_periodo;
            }
            set
            {
                Onnum_periodoChanging(value);
                ReportPropertyChanging("num_periodo");
                _num_periodo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_periodo");
                Onnum_periodoChanged();
            }
        }
        private Nullable<global::System.Int32> _num_periodo;
        partial void Onnum_periodoChanging(Nullable<global::System.Int32> value);
        partial void Onnum_periodoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Solicitud_Periodo", "SIFSolicitud")]
        public EntityCollection<SIFSolicitud> SIFSolicituds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SIFSolicitud>("Inclutec_BDModel.FK_Solicitud_Periodo", "SIFSolicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SIFSolicitud>("Inclutec_BDModel.FK_Solicitud_Periodo", "SIFSolicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Inclutec_BDModel", Name="SIFSolicitud")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIFSolicitud : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIFSolicitud object.
        /// </summary>
        /// <param name="id_Solicitud">Initial value of the id_Solicitud property.</param>
        /// <param name="txt_curso">Initial value of the txt_curso property.</param>
        /// <param name="txt_estado">Initial value of the txt_estado property.</param>
        /// <param name="fec_creacion">Initial value of the fec_creacion property.</param>
        /// <param name="fK_Estudiante_carnet">Initial value of the FK_Estudiante_carnet property.</param>
        /// <param name="fK_Periodo_idPeriodo">Initial value of the FK_Periodo_idPeriodo property.</param>
        public static SIFSolicitud CreateSIFSolicitud(global::System.Int32 id_Solicitud, global::System.String txt_curso, global::System.String txt_estado, global::System.DateTime fec_creacion, global::System.String fK_Estudiante_carnet, global::System.Int32 fK_Periodo_idPeriodo)
        {
            SIFSolicitud sIFSolicitud = new SIFSolicitud();
            sIFSolicitud.id_Solicitud = id_Solicitud;
            sIFSolicitud.txt_curso = txt_curso;
            sIFSolicitud.txt_estado = txt_estado;
            sIFSolicitud.fec_creacion = fec_creacion;
            sIFSolicitud.FK_Estudiante_carnet = fK_Estudiante_carnet;
            sIFSolicitud.FK_Periodo_idPeriodo = fK_Periodo_idPeriodo;
            return sIFSolicitud;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Solicitud
        {
            get
            {
                return _id_Solicitud;
            }
            set
            {
                if (_id_Solicitud != value)
                {
                    Onid_SolicitudChanging(value);
                    ReportPropertyChanging("id_Solicitud");
                    _id_Solicitud = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Solicitud");
                    Onid_SolicitudChanged();
                }
            }
        }
        private global::System.Int32 _id_Solicitud;
        partial void Onid_SolicitudChanging(global::System.Int32 value);
        partial void Onid_SolicitudChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txt_comentario
        {
            get
            {
                return _txt_comentario;
            }
            set
            {
                Ontxt_comentarioChanging(value);
                ReportPropertyChanging("txt_comentario");
                _txt_comentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txt_comentario");
                Ontxt_comentarioChanged();
            }
        }
        private global::System.String _txt_comentario;
        partial void Ontxt_comentarioChanging(global::System.String value);
        partial void Ontxt_comentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String txt_curso
        {
            get
            {
                return _txt_curso;
            }
            set
            {
                Ontxt_cursoChanging(value);
                ReportPropertyChanging("txt_curso");
                _txt_curso = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("txt_curso");
                Ontxt_cursoChanged();
            }
        }
        private global::System.String _txt_curso;
        partial void Ontxt_cursoChanging(global::System.String value);
        partial void Ontxt_cursoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txt_motivo
        {
            get
            {
                return _txt_motivo;
            }
            set
            {
                Ontxt_motivoChanging(value);
                ReportPropertyChanging("txt_motivo");
                _txt_motivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txt_motivo");
                Ontxt_motivoChanged();
            }
        }
        private global::System.String _txt_motivo;
        partial void Ontxt_motivoChanging(global::System.String value);
        partial void Ontxt_motivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String txt_estado
        {
            get
            {
                return _txt_estado;
            }
            set
            {
                Ontxt_estadoChanging(value);
                ReportPropertyChanging("txt_estado");
                _txt_estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("txt_estado");
                Ontxt_estadoChanged();
            }
        }
        private global::System.String _txt_estado;
        partial void Ontxt_estadoChanging(global::System.String value);
        partial void Ontxt_estadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fec_creacion
        {
            get
            {
                return _fec_creacion;
            }
            set
            {
                Onfec_creacionChanging(value);
                ReportPropertyChanging("fec_creacion");
                _fec_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fec_creacion");
                Onfec_creacionChanged();
            }
        }
        private global::System.DateTime _fec_creacion;
        partial void Onfec_creacionChanging(global::System.DateTime value);
        partial void Onfec_creacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FK_Estudiante_carnet
        {
            get
            {
                return _FK_Estudiante_carnet;
            }
            set
            {
                OnFK_Estudiante_carnetChanging(value);
                ReportPropertyChanging("FK_Estudiante_carnet");
                _FK_Estudiante_carnet = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FK_Estudiante_carnet");
                OnFK_Estudiante_carnetChanged();
            }
        }
        private global::System.String _FK_Estudiante_carnet;
        partial void OnFK_Estudiante_carnetChanging(global::System.String value);
        partial void OnFK_Estudiante_carnetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FK_Periodo_idPeriodo
        {
            get
            {
                return _FK_Periodo_idPeriodo;
            }
            set
            {
                OnFK_Periodo_idPeriodoChanging(value);
                ReportPropertyChanging("FK_Periodo_idPeriodo");
                _FK_Periodo_idPeriodo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Periodo_idPeriodo");
                OnFK_Periodo_idPeriodoChanged();
            }
        }
        private global::System.Int32 _FK_Periodo_idPeriodo;
        partial void OnFK_Periodo_idPeriodoChanging(global::System.Int32 value);
        partial void OnFK_Periodo_idPeriodoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Solicitud_Estudiante", "SIFEstudiante")]
        public SIFEstudiante SIFEstudiante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFEstudiante>("Inclutec_BDModel.FK_Solicitud_Estudiante", "SIFEstudiante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFEstudiante>("Inclutec_BDModel.FK_Solicitud_Estudiante", "SIFEstudiante").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SIFEstudiante> SIFEstudianteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFEstudiante>("Inclutec_BDModel.FK_Solicitud_Estudiante", "SIFEstudiante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SIFEstudiante>("Inclutec_BDModel.FK_Solicitud_Estudiante", "SIFEstudiante", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Grupo_Por_Solicitud_Solicitud", "SIFGrupo_Por_Solicitud")]
        public SIFGrupo_Por_Solicitud SIFGrupo_Por_Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFGrupo_Por_Solicitud").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFGrupo_Por_Solicitud").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SIFGrupo_Por_Solicitud> SIFGrupo_Por_SolicitudReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFGrupo_Por_Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SIFGrupo_Por_Solicitud>("Inclutec_BDModel.FK_Grupo_Por_Solicitud_Solicitud", "SIFGrupo_Por_Solicitud", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Inclutec_BDModel", "FK_Solicitud_Periodo", "SIFPeriodo")]
        public SIFPeriodo SIFPeriodo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFPeriodo>("Inclutec_BDModel.FK_Solicitud_Periodo", "SIFPeriodo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFPeriodo>("Inclutec_BDModel.FK_Solicitud_Periodo", "SIFPeriodo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SIFPeriodo> SIFPeriodoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SIFPeriodo>("Inclutec_BDModel.FK_Solicitud_Periodo", "SIFPeriodo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SIFPeriodo>("Inclutec_BDModel.FK_Solicitud_Periodo", "SIFPeriodo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Inclutec_BDModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
